use crate::report::{BatchReport, FileReport, ReviewState};
use crate::suggestions::FixSuggestion;
use crate::validate::{Finding, Severity, Status};
use std::path::Path;

pub fn write_html_report(report: &BatchReport, path: &Path) -> Result<(), String> {
    let html = render_html(report);
    std::fs::write(path, html).map_err(|e| e.to_string())
}

fn render_html(report: &BatchReport) -> String {
    let overall = report.overall_status();
    let generated = chrono_lite_timestamp();
    let batch_findings = render_batch_findings(report);
    let file_index = render_file_index(report);
    let file_sections = report
        .files
        .iter()
        .enumerate()
        .map(|(index, file)| render_file_section(file, index))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Media QA Report — {profile}</title>
  <style>{css}</style>
</head>
<body>
  <div class="page">
    <header class="report-header">
      <div class="report-header-copy">
        <p class="eyebrow">Delivery QC report</p>
        <h1>Media QA Report</h1>
        <p class="subtitle">Profile <strong>{profile}</strong> · Generated {generated}</p>
      </div>
      <div class="verdict-pill {overall_class}">{overall_label}</div>
    </header>

    <section class="stats" aria-label="Batch summary">
      {stats}
    </section>

    {batch_findings}

    {file_index}

    <section class="files" aria-label="Per-file results">
      <div class="section-heading">
        <h2>File results</h2>
        <p>{file_count} file{file_plural} checked against <strong>{profile}</strong></p>
      </div>
      {file_sections}
    </section>

    <footer class="report-footer">
      <p>Generated by <strong>mediaqa</strong> · Post-production delivery QC</p>
    </footer>
  </div>
</body>
</html>"#,
        profile = html_escape(&report.profile),
        css = REPORT_CSS,
        generated = generated,
        overall_class = status_class(overall),
        overall_label = status_label(overall),
        stats = render_stats(report),
        batch_findings = batch_findings,
        file_index = file_index,
        file_count = report.summary.total,
        file_plural = if report.summary.total == 1 { "" } else { "s" },
        file_sections = file_sections,
    )
}

fn render_stats(report: &BatchReport) -> String {
    let s = &report.summary;
    format!(
        r#"<article class="stat-card"><span class="stat-value">{total}</span><span class="stat-label">Total</span></article>
<article class="stat-card stat-pass"><span class="stat-value">{passed}</span><span class="stat-label">Passed</span></article>
<article class="stat-card stat-warn"><span class="stat-value">{warned}</span><span class="stat-label">Warnings</span></article>
<article class="stat-card stat-fail"><span class="stat-value">{failed}</span><span class="stat-label">Failed</span></article>
<article class="stat-card stat-error"><span class="stat-value">{errors}</span><span class="stat-label">Errors</span></article>
<article class="stat-card stat-attention"><span class="stat-value">{attention}</span><span class="stat-label">Needs review</span></article>"#,
        total = s.total,
        passed = s.passed,
        warned = s.warned,
        failed = s.failed,
        errors = s.errors,
        attention = s.needs_human_attention,
    )
}

fn render_batch_findings(report: &BatchReport) -> String {
    if report.batch_findings.is_empty() {
        return String::new();
    }

    let items = report
        .batch_findings
        .iter()
        .map(render_finding_item)
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<section class="batch-findings">
  <div class="section-heading">
    <h2>Batch issues</h2>
    <p>Problems that span multiple files in this export</p>
  </div>
  <ul class="finding-list">{items}</ul>
</section>"#,
        items = items,
    )
}

fn render_file_index(report: &BatchReport) -> String {
    if report.files.len() <= 1 {
        return String::new();
    }

    let links = report
        .files
        .iter()
        .enumerate()
        .map(|(index, file)| {
            let anchor = format!("file-{index}");
            let href = format!("#{}", anchor);
            format!(
                r#"<a class="file-link {status_class}" href="{href}"><span class="file-link-name">{name}</span><span class="badge badge-sm {status_class}">{status}</span></a>"#,
                href = html_escape(&href),
                name = html_escape(&file_basename(&file.path)),
                status_class = status_class(file.status),
                status = status_label(file.status),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<nav class="file-index" aria-label="Jump to file">
  <div class="section-heading">
    <h2>Quick navigation</h2>
    <p>Jump to a file in this batch</p>
  </div>
  <div class="file-link-grid">{links}</div>
</nav>"#,
        links = links,
    )
}

fn render_file_section(file: &FileReport, index: usize) -> String {
    let anchor = format!("file-{index}");
    let basename = file_basename(&file.path);
    let full_path = html_escape(&file.path.display().to_string());
    let metadata = render_file_metadata(file);
    let error = file
        .error
        .as_ref()
        .map(|err| {
            format!(
                r#"<div class="runtime-error" role="alert"><strong>Could not complete check</strong><p>{err}</p></div>"#,
                err = html_escape(err),
            )
        })
        .unwrap_or_default();
    let findings = render_findings_block(&file.findings);
    let suggestions = render_suggestions_block(&file.suggestions);
    let open_attr = if matches!(file.status, Status::Fail) || file.error.is_some() {
        " open"
    } else {
        ""
    };

    format!(
        r#"<article class="file-card {status_class}" id="{anchor}">
  <details class="file-details"{open_attr}>
    <summary class="file-summary">
      <div class="file-summary-main">
        <span class="badge {status_class}">{status}</span>
        <div class="file-title-wrap">
          <h3 class="file-title">{basename}</h3>
          <p class="file-path">{full_path}</p>
        </div>
      </div>
      <div class="file-summary-meta">
        <span class="review-pill {review_class}">{review}</span>
        <span class="finding-count">{finding_count}</span>
      </div>
    </summary>
    <div class="file-body">
      {metadata}
      {error}
      {findings}
      {suggestions}
    </div>
  </details>
</article>"#,
        status_class = status_class(file.status),
        status = status_label(file.status),
        basename = html_escape(&basename),
        full_path = full_path,
        review_class = review_class(file.review_state),
        review = review_label(file.review_state),
        finding_count = finding_count_label(file.findings.len()),
        metadata = metadata,
        error = error,
        findings = findings,
        suggestions = suggestions,
        open_attr = open_attr,
        anchor = anchor,
    )
}

fn render_file_metadata(file: &FileReport) -> String {
    let mut chips = Vec::new();

    if let (Some(width), Some(height)) = (file.width, file.height) {
        chips.push(format!("{width}×{height}"));
    }
    if let Some(codec) = &file.video_codec {
        chips.push(html_escape(codec));
    }
    if let Some(bytes) = file.file_size_bytes {
        chips.push(format_file_size(bytes));
    }

    if chips.is_empty() {
        return String::new();
    }

    let chip_html = chips
        .iter()
        .map(|chip| format!(r#"<span class="meta-chip">{chip}</span>"#))
        .collect::<Vec<_>>()
        .join("");

    format!(r#"<div class="file-meta">{chip_html}</div>"#, chip_html = chip_html)
}

fn render_findings_block(findings: &[Finding]) -> String {
    if findings.is_empty() {
        return r#"<section class="block block-clean">
  <h4>Findings</h4>
  <p class="empty-state">No delivery issues detected for this file.</p>
</section>"#
            .into();
    }

    let items = findings
        .iter()
        .map(render_finding_item)
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<section class="block">
  <h4>Findings</h4>
  <ul class="finding-list">{items}</ul>
</section>"#,
        items = items,
    )
}

fn render_suggestions_block(suggestions: &[FixSuggestion]) -> String {
    if suggestions.is_empty() {
        return String::new();
    }

    let items = suggestions
        .iter()
        .map(|suggestion| {
            format!(
                r#"<li class="suggestion-item"><span class="suggestion-code">{code}</span><p>{text}</p></li>"#,
                code = html_escape(&suggestion.code),
                text = html_escape(&suggestion.suggestion),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"<section class="block block-suggestions">
  <h4>Suggested fixes</h4>
  <ul class="suggestion-list">{items}</ul>
</section>"#,
        items = items,
    )
}

fn render_finding_item(finding: &Finding) -> String {
    format!(
        r#"<li class="finding-item {severity_class}">
  <div class="finding-head">
    <span class="badge badge-sm {severity_class}">{severity}</span>
    <code class="finding-code">{code}</code>
  </div>
  <p class="finding-message">{message}</p>
</li>"#,
        severity_class = severity_class(finding.severity),
        severity = severity_label(finding.severity),
        code = html_escape(&finding.code),
        message = html_escape(&finding.message),
    )
}

fn status_class(status: Status) -> &'static str {
    match status {
        Status::Pass => "pass",
        Status::Warn => "warn",
        Status::Fail => "fail",
    }
}

fn status_label(status: Status) -> &'static str {
    match status {
        Status::Pass => "Pass",
        Status::Warn => "Warning",
        Status::Fail => "Fail",
    }
}

fn severity_class(severity: Severity) -> &'static str {
    match severity {
        Severity::Warn => "warn",
        Severity::Fail => "fail",
    }
}

fn severity_label(severity: Severity) -> &'static str {
    match severity {
        Severity::Warn => "Warning",
        Severity::Fail => "Fail",
    }
}

fn review_class(state: ReviewState) -> &'static str {
    match state {
        ReviewState::Pass => "pass",
        ReviewState::Warn => "warn",
        ReviewState::NeedsHumanAttention => "attention",
    }
}

fn review_label(state: ReviewState) -> &'static str {
    match state {
        ReviewState::Pass => "Ready to deliver",
        ReviewState::Warn => "Review warnings",
        ReviewState::NeedsHumanAttention => "Needs human review",
    }
}

fn finding_count_label(count: usize) -> String {
    if count == 0 {
        "No findings".into()
    } else if count == 1 {
        "1 finding".into()
    } else {
        format!("{count} findings")
    }
}

fn file_basename(path: &Path) -> String {
    path.file_name()
        .and_then(|name| name.to_str())
        .map(str::to_string)
        .unwrap_or_else(|| path.display().to_string())
}

fn format_file_size(bytes: u64) -> String {
    const KB: f64 = 1024.0;
    const MB: f64 = KB * 1024.0;
    const GB: f64 = MB * 1024.0;
    let size = bytes as f64;
    if size >= GB {
        format!("{:.2} GB", size / GB)
    } else if size >= MB {
        format!("{:.2} MB", size / MB)
    } else if size >= KB {
        format!("{:.1} KB", size / KB)
    } else {
        format!("{bytes} B")
    }
}

fn chrono_lite_timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let seconds = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0);
    format_unix_timestamp(seconds)
}

fn format_unix_timestamp(seconds: u64) -> String {
    let days_since_epoch = seconds / 86_400;
    let time_of_day = seconds % 86_400;
    let hour = time_of_day / 3600;
    let minute = (time_of_day % 3600) / 60;

    let mut year = 1970i32;
    let mut remaining_days = days_since_epoch as i32;

    loop {
        let days_in_year = if is_leap_year(year) { 366 } else { 365 };
        if remaining_days < days_in_year {
            break;
        }
        remaining_days -= days_in_year;
        year += 1;
    }

    let month_lengths = if is_leap_year(year) {
        [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    } else {
        [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    };

    let mut month = 1u32;
    for length in month_lengths {
        if remaining_days < length {
            break;
        }
        remaining_days -= length;
        month += 1;
    }

    let day = remaining_days + 1;
    format!(
        "{year:04}-{month:02}-{day:02} {hour:02}:{minute:02} UTC",
        day = day,
        month = month,
        year = year,
        hour = hour,
        minute = minute,
    )
}

fn is_leap_year(year: i32) -> bool {
    (year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)
}

fn html_escape(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const REPORT_CSS: &str = r#"
:root {
  color-scheme: dark;
  --bg: #0b1017;
  --surface: #121a24;
  --surface-raised: #182230;
  --border: #2a3548;
  --text: #e8edf5;
  --muted: #93a0b8;
  --pass: #4ade80;
  --pass-bg: rgba(74, 222, 128, 0.12);
  --warn: #fbbf24;
  --warn-bg: rgba(251, 191, 36, 0.12);
  --fail: #f87171;
  --fail-bg: rgba(248, 113, 113, 0.12);
  --accent: #60a5fa;
  --shadow: 0 18px 48px rgba(0, 0, 0, 0.28);
}

* { box-sizing: border-box; }

body {
  margin: 0;
  font-family: "SF Pro Text", "Segoe UI", system-ui, sans-serif;
  background:
    radial-gradient(circle at top left, rgba(96, 165, 250, 0.08), transparent 28%),
    linear-gradient(180deg, #0d131c 0%, var(--bg) 100%);
  color: var(--text);
  line-height: 1.5;
}

.page {
  width: min(1080px, calc(100vw - 32px));
  margin: 0 auto;
  padding: 32px 0 48px;
}

.report-header,
.stats,
.batch-findings,
.file-index,
.files,
.report-footer {
  margin-bottom: 24px;
}

.report-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 20px;
  padding: 28px 30px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 18px;
  box-shadow: var(--shadow);
}

.eyebrow {
  margin: 0 0 6px;
  font-size: 0.78rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--accent);
  font-weight: 700;
}

.report-header h1 {
  margin: 0;
  font-size: clamp(1.8rem, 3vw, 2.4rem);
  line-height: 1.1;
}

.subtitle {
  margin: 10px 0 0;
  color: var(--muted);
}

.verdict-pill {
  flex-shrink: 0;
  padding: 10px 16px;
  border-radius: 999px;
  font-size: 0.92rem;
  font-weight: 700;
  letter-spacing: 0.03em;
  text-transform: uppercase;
  border: 1px solid transparent;
}

.verdict-pill.pass { color: var(--pass); background: var(--pass-bg); border-color: rgba(74, 222, 128, 0.28); }
.verdict-pill.warn { color: var(--warn); background: var(--warn-bg); border-color: rgba(251, 191, 36, 0.28); }
.verdict-pill.fail { color: var(--fail); background: var(--fail-bg); border-color: rgba(248, 113, 113, 0.28); }

.stats {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 12px;
}

.stat-card {
  padding: 18px 16px;
  border-radius: 14px;
  background: var(--surface);
  border: 1px solid var(--border);
}

.stat-value {
  display: block;
  font-size: 1.8rem;
  font-weight: 700;
  line-height: 1;
}

.stat-label {
  display: block;
  margin-top: 8px;
  color: var(--muted);
  font-size: 0.86rem;
}

.stat-pass .stat-value { color: var(--pass); }
.stat-warn .stat-value { color: var(--warn); }
.stat-fail .stat-value { color: var(--fail); }
.stat-error .stat-value { color: #fb7185; }
.stat-attention .stat-value { color: var(--accent); }

.section-heading {
  margin-bottom: 14px;
}

.section-heading h2 {
  margin: 0 0 4px;
  font-size: 1.15rem;
}

.section-heading p {
  margin: 0;
  color: var(--muted);
  font-size: 0.92rem;
}

.batch-findings,
.file-index,
.file-card {
  padding: 20px;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 16px;
}

.file-link-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 10px;
}

.file-link {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  padding: 12px 14px;
  border-radius: 12px;
  text-decoration: none;
  color: var(--text);
  background: var(--surface-raised);
  border: 1px solid var(--border);
}

.file-link:hover {
  border-color: rgba(96, 165, 250, 0.45);
}

.file-link-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-size: 0.92rem;
}

.files {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.file-card.pass { border-color: rgba(74, 222, 128, 0.18); }
.file-card.warn { border-color: rgba(251, 191, 36, 0.22); }
.file-card.fail { border-color: rgba(248, 113, 113, 0.24); }

.file-details {
  border-radius: 12px;
}

.file-summary {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  cursor: pointer;
  list-style: none;
}

.file-summary::-webkit-details-marker { display: none; }

.file-summary-main {
  display: flex;
  align-items: flex-start;
  gap: 14px;
  min-width: 0;
}

.file-title-wrap { min-width: 0; }

.file-title {
  margin: 0;
  font-size: 1rem;
  word-break: break-word;
}

.file-path {
  margin: 4px 0 0;
  color: var(--muted);
  font-size: 0.82rem;
  word-break: break-all;
}

.file-summary-meta {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  gap: 8px;
  flex-shrink: 0;
}

.finding-count {
  color: var(--muted);
  font-size: 0.82rem;
}

.file-body {
  margin-top: 18px;
  padding-top: 18px;
  border-top: 1px solid var(--border);
}

.file-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 16px;
}

.meta-chip {
  display: inline-flex;
  align-items: center;
  padding: 5px 10px;
  border-radius: 999px;
  background: var(--surface-raised);
  border: 1px solid var(--border);
  color: var(--muted);
  font-size: 0.8rem;
}

.badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 5px 10px;
  border-radius: 999px;
  font-size: 0.74rem;
  font-weight: 700;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  border: 1px solid transparent;
}

.badge-sm {
  padding: 3px 8px;
  font-size: 0.68rem;
}

.badge.pass, .review-pill.pass { color: var(--pass); background: var(--pass-bg); border-color: rgba(74, 222, 128, 0.24); }
.badge.warn, .review-pill.warn { color: var(--warn); background: var(--warn-bg); border-color: rgba(251, 191, 36, 0.24); }
.badge.fail, .review-pill.attention { color: var(--fail); background: var(--fail-bg); border-color: rgba(248, 113, 113, 0.24); }

.review-pill {
  display: inline-flex;
  padding: 6px 10px;
  border-radius: 999px;
  font-size: 0.76rem;
  font-weight: 600;
  border: 1px solid transparent;
}

.review-pill.attention {
  color: var(--accent);
  background: rgba(96, 165, 250, 0.12);
  border-color: rgba(96, 165, 250, 0.24);
}

.runtime-error {
  margin-bottom: 16px;
  padding: 14px 16px;
  border-radius: 12px;
  background: var(--fail-bg);
  border: 1px solid rgba(248, 113, 113, 0.28);
}

.runtime-error p {
  margin: 6px 0 0;
  color: #fecaca;
}

.block + .block {
  margin-top: 18px;
}

.block h4 {
  margin: 0 0 10px;
  font-size: 0.92rem;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

.empty-state {
  margin: 0;
  color: var(--muted);
}

.finding-list,
.suggestion-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.finding-item,
.suggestion-item {
  padding: 14px 16px;
  border-radius: 12px;
  background: var(--surface-raised);
  border: 1px solid var(--border);
}

.finding-item.warn { border-color: rgba(251, 191, 36, 0.22); }
.finding-item.fail { border-color: rgba(248, 113, 113, 0.24); }

.finding-head {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 8px;
}

.finding-code,
.suggestion-code {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.8rem;
  color: var(--accent);
}

.finding-message,
.suggestion-item p {
  margin: 0;
}

.block-suggestions {
  padding: 16px;
  border-radius: 12px;
  background: rgba(96, 165, 250, 0.06);
  border: 1px solid rgba(96, 165, 250, 0.16);
}

.suggestion-item {
  display: grid;
  gap: 6px;
}

.report-footer {
  padding: 16px 4px 0;
  color: var(--muted);
  font-size: 0.86rem;
  text-align: center;
}

@media (max-width: 720px) {
  .report-header,
  .file-summary {
    flex-direction: column;
    align-items: stretch;
  }

  .file-summary-meta {
    align-items: flex-start;
  }

  .verdict-pill {
    align-self: flex-start;
  }
}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::report::{BatchSummary, FileReport};
    use crate::validate::{Finding, Severity, Status};
    use std::path::PathBuf;

    fn sample_report() -> BatchReport {
        BatchReport {
            profile: "youtube".into(),
            files: vec![
                FileReport {
                    path: PathBuf::from("exports/clip_a.mp4"),
                    status: Status::Pass,
                    review_state: ReviewState::Pass,
                    findings: vec![],
                    suggestions: vec![],
                    error: None,
                    width: Some(1920),
                    height: Some(1080),
                    video_codec: Some("h264".into()),
                    file_size_bytes: Some(1_500_000),
                },
                FileReport {
                    path: PathBuf::from("exports/clip_b.mp4"),
                    status: Status::Fail,
                    review_state: ReviewState::NeedsHumanAttention,
                    findings: vec![Finding {
                        code: "RESOLUTION_MISMATCH".into(),
                        severity: Severity::Fail,
                        message: "Expected 1920x1080, got 1280x720".into(),
                    }],
                    suggestions: vec![crate::suggestions::FixSuggestion {
                        code: "RESOLUTION_MISMATCH".into(),
                        suggestion: "Re-export at the profile resolution before delivery.".into(),
                    }],
                    error: None,
                    width: Some(1280),
                    height: Some(720),
                    video_codec: Some("h264".into()),
                    file_size_bytes: Some(900_000),
                },
            ],
            summary: BatchSummary {
                total: 2,
                passed: 1,
                warned: 0,
                failed: 1,
                errors: 0,
                needs_human_attention: 1,
            },
            batch_findings: vec![Finding {
                code: "BATCH_MIXED_RESOLUTION".into(),
                severity: Severity::Warn,
                message: "Batch contains mixed resolutions".into(),
            }],
        }
    }

    #[test]
    fn html_report_includes_summary_and_navigation() {
        let html = render_html(&sample_report());
        assert!(html.contains("Media QA Report"));
        assert!(html.contains("clip_a.mp4"));
        assert!(html.contains("Quick navigation"));
        assert!(html.contains("Batch issues"));
        assert!(html.contains("Suggested fixes"));
        assert!(html.contains("1920×1080"));
    }

    #[test]
    fn html_escape_protects_markup() {
        assert_eq!(
            html_escape("<script>&\"</script>"),
            "&lt;script&gt;&amp;&quot;&lt;/script&gt;"
        );
    }
}
